-- 코드를 입력하세요
SELECT BOOK.CATEGORY, SUM(BOOK_SALES.SALES)
FROM BOOK, BOOK_SALES
WHERE MONTH(SALES_DATE) = 01 AND YEAR(SALES_DATE) = 2022 AND BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY